name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      matrix:
        os: [windows-latest, ubuntu-18.04]
    
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
        
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        # SDK Version to use; x will use the latest version of the 5.0 channel
        dotnet-version: 5.0.x 
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
